name: Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
          python-version: 3.8

    - name: upgrade pip and install poetry
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install poetry poetry-dynamic-versioning


    - name: install dependencies
      run: |
        make dist



