name: Publish
on: "push"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
          python-version: 3.8

    - name: upgrade pip and install poetry
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install poetry poetry-dynamic-versioning

    - name: Cache poetry packages
      uses: actions/cache@v1
      with:
          path: ~/.venv
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

    - name: install dependencies
      run: |
        make install

    - name: Set PACKAGE_VERSION env var
      run: echo ::set-env name=PACKAGE_VERSION::$(poetry run python scripts/calculate_version.py)
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: create release
      id: create-release
      if: github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      continue-on-error: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: ${{ env.PACKAGE_VERSION }}

