name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    name: ${{ matrix.lang }} tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        lang: [Python]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: upgrade pip and install poetry
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install poetry

    - name: cache packages
      uses: actions/cache@v1
      with:
          path: ~/.venv
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

    - name: install dependencies
      run: |
        make install

    - name: check lint
      run: |
        make lint

    - name: run tests
      run: |
        make test
